// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFile(arg1) {
  return window['go']['main']['App']['AddFile'](arg1);
}

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function ListLocalFiles() {
  return window['go']['main']['App']['ListLocalFiles']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
