// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFile(arg1:string):Promise<string>;

export function DownloadFile(arg1:string):Promise<void>;

export function ListLocalFiles():Promise<Array<main.LocalFileFE>>;

export function SelectFile():Promise<string>;
